---
title: "lab-07-simpsons.Rmd"
author: "hajar eid "
date: "3 March 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r load_libraries, message=FALSE}
library(tidyverse) 
library(mosaicData)
```


## Exercises


1.  
```{r whickam}
?Whickham
```
    
Your answer:
Observational , because the data is observational  description states that is based on age, smoking, and mortality, which are all observable events and not produced via experiments.

2.  
```{r observations}
nrow(Whickham)
```

Your answer;
obs 1314 var 3

3.  

```{r number_variables}
names(Whickham)
```

Your answer: there are 3 variable  "outcome" "smoker" "age"

```{r var_type}
ggplot(Whickham, aes(x = outcome)) +
  geom_bar()
```

Your answer: 

```{r plot_outcome}
ggplot(Whickham, aes(x = smoker)) +
  geom_bar()
```


```{r plot_smoker}
ggplot(Whickham, aes(x = age)) +
  geom_boxplot()
```

```{r plot_age}
unique(Whickham$outcome)
unique(Whickham$smoker)
unique(Whickham$age)
```


4. 

```{r plot_smokeVSincome_1}
ggplot(data=Whickham, aes(x=smoker, y=outcome, color=outcome)) + geom_bar(stat="identity")
```

Knit, commit, and push to github.

5. 

```{r plot_smokeVSincome_2}
Whickham %>%
  count(smoker, outcome)
```

6.

```{r age_cat}
Whickham <- Whickham%>% mutate (age_cat = case_when (age <= 44 ~ "18-44", age > 44. & age <= 64 ~ "45-64", age > 64 ~ "65+"))
```

7. 

```{r plot_smokeVSincome_3}
ggplot(data=Whickham, aes(x=outcome, y=smoker,color=smoker, fill=age_cat)) + geom_bar(stat="identity") +facet_wrap(~age_cat)
```

Knit, commit, and push to github.